## 人工智能时代媒体行业的技能与未来就业:基于机器学习和网络分析

### 1.machine learning（computerization）

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_1=open('/Users/Asus/Desktop/文件夹/项目/人工智能时代媒体就业/data/onet_db_23_2_text/Skills.txt')
df_s = pd.read_csv(df_1, sep = '\t')
df_s=df_s[df_s['Scale ID']=='LV']
df_s=df_s[df_s['Element Name'].isin(['Social Perceptiveness','Negotiation','Persuasion'])]
# df_s=df_s[['O*NET-SOC Code','Element Name','Data Value']]
# df_s.head()

## len(df_s['O*NET-SOC Code'])
df_2=pd.read_excel('/Users/Asus/Desktop/文件夹/项目/人工智能时代媒体就业/data/onet_db_23_2_text/2010_to_2018_SOC_Crosswalk.xlsx')
##df_2.head()
df_2=df_2.rename(columns={'O*NET-SOC 2010 Code':'O*NET-SOC Code'})
df_s1=df_s.merge(df_2,how='left',on='O*NET-SOC Code')
##df_s1
df_s1=df_s1.rename(columns={'2018 SOC Code':'soc'})
df_3=pd.read_excel('/Users/Asus/Desktop/文件夹/项目/人工智能时代媒体就业/data/onet_db_23_2_text/future_of_employment_appendix_data.xlsx')
df_3.head()
df_s2=df_3.merge(df_s1,how='left',on='soc')
df_s2.head()

,id,computerization,label,soc,occupation,O*NET-SOC Code,Element ID,Element Name,Scale ID,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source,O*NET-SOC 2010 Title,2018 SOC Title
0,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.00,2.B.1.a,Social Perceptiveness,LV,4.00,8.0,0.19,3.63,4.37,N,N,07/2016,Analyst,Recreational Therapists,Recreational Therapists
1,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.00,2.B.1.c,Persuasion,LV,3.75,8.0,0.16,3.43,4.07,N,N,07/2016,Analyst,Recreational Therapists,Recreational Therapists
2,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.00,2.B.1.d,Negotiation,LV,3.25,8.0,0.16,2.93,3.57,N,N,07/2016,Analyst,Recreational Therapists,Recreational Therapists
3,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.01,2.B.1.a,Social Perceptiveness,LV,4.88,8.0,0.30,4.30,5.45,N,N,07/2014,Analyst,Art Therapists,Recreational Therapists
4,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.01,2.B.1.c,Persuasion,LV,3.38,8.0,0.18,3.02,3.73,N,N,07/2014,Analyst,Art Therapists,Recreational Therapists

In [3]:

df_a=open('/Users/Asus/Desktop/文件夹/项目/人工智能时代媒体就业/data/onet_db_23_2_text/Abilities.txt')
df_a = pd.read_csv(df_a, sep = '\t')
df_a=df_a[df_a['Scale ID']=='LV']
df_a=df_a[df_a['Element Name'].isin(['Finger Dexterity','Manual Dexterity','Originality'])]
# df_a=df_a[['O*NET-SOC Code','Element Name','Data Value']]
# df_a.head()
df_a1=df_a.merge(df_2,how='left',on='O*NET-SOC Code')
df_a1=df_a1.rename(columns={'2018 SOC Code':'soc'})
df_a2=df_3.merge(df_a1,how='left',on='soc')
df_a2.head()

,id,computerization,label,soc,occupation,O*NET-SOC Code,Element ID,Element Name,Scale ID,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source,O*NET-SOC 2010 Title,2018 SOC Title
0,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.00,1.A.1.b.2,Originality,LV,3.88,8.0,0.13,3.63,4.12,N,N,07/2016,Analyst,Recreational Therapists,Recreational Therapists
1,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.00,1.A.2.a.2,Manual Dexterity,LV,2.12,8.0,0.13,1.88,2.37,N,N,07/2016,Analyst,Recreational Therapists,Recreational Therapists
2,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.00,1.A.2.a.3,Finger Dexterity,LV,2.62,8.0,0.18,2.27,2.98,N,N,07/2016,Analyst,Recreational Therapists,Recreational Therapists
3,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.01,1.A.1.b.2,Originality,LV,3.75,8.0,0.16,3.43,4.07,N,N,07/2014,Analyst,Art Therapists,Recreational Therapists
4,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.01,1.A.2.a.2,Manual Dexterity,LV,2.25,8.0,0.16,1.93,2.57,N,N,07/2014,Analyst,Art Therapists,Recreational Therapists

In [4]:

df_k=open('/Users/Asus/Desktop/文件夹/项目/人工智能时代媒体就业/data/onet_db_23_2_text/Knowledge.txt')
df_k = pd.read_csv(df_k, sep = '\t')
df_k=df_k[df_k['Scale ID']=='LV']
df_k=df_k[df_k['Element Name']=='Fine Arts']

# df_a.head()
df_k1=df_k.merge(df_2,how='left',on='O*NET-SOC Code')
df_k1=df_k1.rename(columns={'2018 SOC Code':'soc'})
df_k2=df_3.merge(df_k1,how='left',on='soc')
df_k2.head()

,id,computerization,label,soc,occupation,O*NET-SOC Code,Element ID,Element Name,Scale ID,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source,O*NET-SOC 2010 Title,2018 SOC Title
0,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.00,2.C.7.c,Fine Arts,LV,2.19,26.0,NaN,NaN,NaN,NaN,N,07/2016,Occupational Expert,Recreational Therapists,Recreational Therapists
1,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.01,2.C.7.c,Fine Arts,LV,4.81,21.0,NaN,NaN,NaN,NaN,N,07/2014,Occupational Expert,Art Therapists,Recreational Therapists
2,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.02,2.C.7.c,Fine Arts,LV,5.66,56.0,NaN,NaN,NaN,NaN,N,07/2014,Occupational Expert,Music Therapists,Recreational Therapists
3,2,0.0030,NaN,49-1011,"First-line supervisors of mechanics, installer...",49-1011.00,2.C.7.c,Fine Arts,LV,0.19,56.0,0.11,0.0,0.41,Y,Y,07/2013,Incumbent,"First-Line Supervisors of Mechanics, Installer...","First-Line Supervisors of Mechanics, Installer..."
4,3,0.0030,NaN,11-9161,Emergency management directors,11-9161.00,2.C.7.c,Fine Arts,LV,0.48,25.0,NaN,NaN,NaN,NaN,Y,07/2017,Occupational Expert,Emergency Management Directors,Emergency Management Directors

In [5]:
df_w=open('/Users/Asus/Desktop/文件夹/项目/人工智能时代媒体就业/data/onet_db_23_2_text/Work Activities.txt')
df_w = pd.read_csv(df_w, sep = '\t')
df_w=df_w[df_w['Scale ID']=='IM']
df_w=df_w[df_w['Element Name']=='Assisting and Caring for Others']

# df_a.head()
df_w1=df_w.merge(df_2,how='left',on='O*NET-SOC Code')
df_w1=df_w1.rename(columns={'2018 SOC Code':'soc'})
df_w2=df_3.merge(df_w1,how='left',on='soc')
df_w2.head()

,id,computerization,label,soc,occupation,O*NET-SOC Code,Element ID,Element Name,Scale ID,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source,O*NET-SOC 2010 Title,2018 SOC Title
0,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.00,4.A.4.a.5,Assisting and Caring for Others,IM,4.65,26.0,NaN,NaN,NaN,NaN,NaN,07/2016,Occupational Expert,Recreational Therapists,Recreational Therapists
1,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.01,4.A.4.a.5,Assisting and Caring for Others,IM,4.76,21.0,NaN,NaN,NaN,NaN,NaN,07/2014,Occupational Expert,Art Therapists,Recreational Therapists
2,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.02,4.A.4.a.5,Assisting and Caring for Others,IM,4.80,56.0,NaN,NaN,NaN,NaN,NaN,07/2014,Occupational Expert,Music Therapists,Recreational Therapists
3,2,0.0030,NaN,49-1011,"First-line supervisors of mechanics, installer...",49-1011.00,4.A.4.a.5,Assisting and Caring for Others,IM,2.99,38.0,0.24,2.51,3.47,N,NaN,07/2013,Incumbent,"First-Line Supervisors of Mechanics, Installer...","First-Line Supervisors of Mechanics, Installer..."
4,3,0.0030,NaN,11-9161,Emergency management directors,11-9161.00,4.A.4.a.5,Assisting and Caring for Others,IM,3.21,24.0,NaN,NaN,NaN,NaN,NaN,07/2017,Occupational Expert,Emergency Management Directors,Emergency Management Directors

In [6]:
df_c=open('/Users/Asus/Desktop/文件夹/项目/人工智能时代媒体就业/data/onet_db_23_2_text/Work Context.txt')
df_c = pd.read_csv(df_c, sep = '\t')
df_c=df_c[df_c['Element Name']=='Cramped Work Space, Awkward Positions']
df_c=df_c[df_c['Scale ID']=='CX']
df_c
df_c1=df_c.merge(df_2,how='left',on='O*NET-SOC Code')
df_c1=df_c1.rename(columns={'2018 SOC Code':'soc'})
df_c2=df_3.merge(df_c1,how='left',on='soc')
df_c2.head()

,id,computerization,label,soc,occupation,O*NET-SOC Code,Element ID,Element Name,Scale ID,Category,...,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source,O*NET-SOC 2010 Title,2018 SOC Title
0,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.00,4.C.2.b.1.e,"Cramped Work Space, Awkward Positions",CX,NaN,...,26.0,NaN,NaN,NaN,NaN,NaN,07/2016,Occupational Expert,Recreational Therapists,Recreational Therapists
1,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.01,4.C.2.b.1.e,"Cramped Work Space, Awkward Positions",CX,NaN,...,20.0,NaN,NaN,NaN,NaN,NaN,07/2014,Occupational Expert,Art Therapists,Recreational Therapists
2,1,0.0028,NaN,29-1125,Recreational therapists,29-1125.02,4.C.2.b.1.e,"Cramped Work Space, Awkward Positions",CX,NaN,...,54.0,NaN,NaN,NaN,NaN,NaN,07/2014,Occupational Expert,Music Therapists,Recreational Therapists
3,2,0.0030,NaN,49-1011,"First-line supervisors of mechanics, installer...",49-1011.00,4.C.2.b.1.e,"Cramped Work Space, Awkward Positions",CX,NaN,...,38.0,0.34,1.92,3.28,N,NaN,07/2013,Incumbent,"First-Line Supervisors of Mechanics, Installer...","First-Line Supervisors of Mechanics, Installer..."
4,3,0.0030,NaN,11-9161,Emergency management directors,11-9161.00,4.C.2.b.1.e,"Cramped Work Space, Awkward Positions",CX,NaN,...,25.0,NaN,NaN,NaN,NaN,NaN,07/2017,Occupational Expert,Emergency Management Directors,Emergency Management Directors

In [7]:
df = pd.concat( [df_s2, df_a2,df_k2,df_w2,df_c2], axis=0 )
df=df.sort_values(by=['O*NET-SOC Code','Element Name'])

df
df_total=df[['id','label','soc','O*NET-SOC Code','Element Name','Data Value','computerization']]
df_total

,id,label,soc,O*NET-SOC Code,Element Name,Data Value,computerization
92,70,0.0,11-1011,11-1011.00,Assisting and Caring for Others,2.18,0.015
92,70,0.0,11-1011,11-1011.00,"Cramped Work Space, Awkward Positions",1.45,0.015
92,70,0.0,11-1011,11-1011.00,Fine Arts,0.87,0.015
262,70,0.0,11-1011,11-1011.00,Finger Dexterity,2.00,0.015
261,70,0.0,11-1011,11-1011.00,Manual Dexterity,0.00,0.015
262,70,0.0,11-1011,11-1011.00,Negotiation,4.62,0.015
260,70,0.0,11-1011,11-1011.00,Originality,4.25,0.015
261,70,0.0,11-1011,11-1011.00,Persuasion,5.00,0.015
260,70,0.0,11-1011,11-1011.00,Social Perceptiveness,4.25,0.015
93,70,0.0,11-1011,11-1011.03,Assisting and Caring for Others,2.23,0.015
93,70,0.0,11-1011,11-1011.03,"Cramped Work Space, Awkward Positions",1.38,0.015
93,70,0.0,11-1011,11-1011.03,Fine Arts,0.96,0.015
265,70,0.0,11-1011,11-1011.03,Finger Dexterity,2.00,0.015
264,70,0.0,11-1011,11-1011.03,Manual Dexterity,0.00,0.015
265,70,0.0,11-1011,11-1011.03,Negotiation,3.25,0.015
263,70,0.0,11-1011,11-1011.03,Originality,4.00,0.015
264,70,0.0,11-1011,11-1011.03,Persuasion,3.88,0.015
263,70,0.0,11-1011,11-1011.03,Social Perceptiveness,3.62,0.015
260,195,NaN,11-1021,11-1021.00,Assisting and Caring for Others,2.94,0.160
260,195,NaN,11-1021,11-1021.00,"Cramped Work Space, Awkward Positions",1.53,0.160
260,195,NaN,11-1021,11-1021.00,Fine Arts,0.47,0.160
736,195,NaN,11-1021,11-1021.00,Finger Dexterity,1.38,0.160
735,195,NaN,11-1021,11-1021.00,Manual Dexterity,0.75,0.160
736,195,NaN,11-1021,11-1021.00,Negotiation,3.62,0.160
734,195,NaN,11-1021,11-1021.00,Originality,3.38,0.160
735,195,NaN,11-1021,11-1021.00,Persuasion,3.50,0.160
734,195,NaN,11-1021,11-1021.00,Social Perceptiveness,4.00,0.160
175,124,NaN,11-2011,11-2011.00,Assisting and Caring for Others,2.37,0.039
175,124,NaN,11-2011,11-2011.00,"Cramped Work Space, Awkward Positions",1.38,0.039
175,124,NaN,11-2011,11-2011.00,Fine Arts,2.30,0.039
...,...,...,...,...,...,...,...
495,382,NaN,51-9122,NaN,NaN,NaN,0.690
503,390,NaN,47-4799,NaN,NaN,NaN,0.710
513,399,NaN,27-3012,NaN,NaN,NaN,0.720
515,401,NaN,11-3011,NaN,NaN,NaN,0.730
520,406,NaN,39-9021,NaN,NaN,NaN,0.740
533,419,NaN,19-4091,NaN,NaN,NaN,0.770
539,425,0.0,45-3021,NaN,NaN,NaN,0.770
542,428,NaN,43-9011,NaN,NaN,NaN,0.780
573,456,NaN,45-3011,NaN,NaN,NaN,0.830
575,458,NaN,53-4021,NaN,NaN,NaN,0.830
608,488,NaN,47-5021,NaN,NaN,NaN,0.850
621,498,1.0,51-4011,NaN,NaN,NaN,0.860
624,501,NaN,45-2090,NaN,NaN,NaN,0.870
648,525,NaN,53-3022,NaN,NaN,NaN,0.890
654,531,1.0,53-3041,NaN,NaN,NaN,0.890
672,541,NaN,13-2021,NaN,NaN,NaN,0.900
681,550,NaN,29-2071,NaN,NaN,NaN,0.910
682,551,NaN,51-9121,NaN,NaN,NaN,0.910
688,557,NaN,19-4041,NaN,NaN,NaN,0.910
702,571,NaN,35-3021,NaN,NaN,NaN,0.920
703,572,NaN,51-9399,NaN,NaN,NaN,0.920
706,575,NaN,51-2091,NaN,NaN,NaN,0.930
710,579,NaN,53-4012,NaN,NaN,NaN,0.930
736,602,NaN,53-7032,NaN,NaN,NaN,0.940
768,632,NaN,35-3022,NaN,NaN,NaN,0.960
777,640,NaN,49-9093,NaN,NaN,NaN,0.960
803,665,NaN,19-4011,NaN,NaN,NaN,0.970
812,673,NaN,27-4013,NaN,NaN,NaN,0.980
831,690,NaN,51-2093,NaN,NaN,NaN,0.980
841,699,NaN,15-2091,NaN,NaN,NaN,0.990

In [8]:
import numpy as np
df_70=df_total.dropna(subset=["label"])
df_70
len(df_70['soc'].unique())
df_70_1=df_70.groupby(['soc','Element Name']).mean()
df_70_1.reset_index(inplace=True)
# df_70_1.to_csv("data.csv")
# df_70_1
# len(df_70_1['soc'].unique())

In [9]:
import pandas as pd 
import pylab as plt
import seaborn as sns
import GPy
import numpy as np

Bad key "text.kerning_factor" on line 4 in
C:\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

In [11]:
data_list=list(df_70_1['Data Value'])
X=[]
for i in range(0,585,9):
    list1=data_list[i:i+9]
    X.append(list1)
len(X)

65

In [12]:
X=np.array(X)
# X

In [13]:
data_list1=list(df_70_1['label'])
Y=[]
for i in range(0,585,9):
    list1=data_list1[i]
    Y.append(list1)
Y=np.array(Y)
Y=Y[:,np.newaxis]
# Y

In [14]:
kernel = GPy.kern.RBF(input_dim=9, variance=1., lengthscale=1.)

In [15]:
m = GPy.models.GPRegression(X,Y,kernel)

In [16]:
m.optimize(messages=True)

HBox(children=(VBox(children=(IntProgress(value=0, max=1000), HTML(value=''))), Box(children=(HTML(value=''),))))

In [17]:
print(m)

Name : GP regression
Objective : 28.130643010163055
Number of Parameters : 3
Number of Optimization Parameters : 3
Updates : True
Parameters:
  GP_regression.           |                value  |  constraints  |  priors
  rbf.variance             |  0.31132427346737634  |      +ve      |
  rbf.lengthscale          |   3.9336163405594933  |      +ve      |
  Gaussian_noise.variance  |   0.0964434513541472  |      +ve      |

In [18]:
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score 
X1, X2, y1, y2 = train_test_split(X, Y, random_state=0,
                                  train_size=0.6, test_size = 0.4)
m = GPy.models.GPRegression(X1,y1,kernel)
m.optimize(messages=True)
y2_model = m.predict(X2)[0]
len(y2_model)

for i in range(len(y2_model)):
        if y2_model[i]>0.5:
            y2_model[i]=1
        else:
            y2_model[i]=0
    
accuracy_score(y2, y2_model)

HBox(children=(VBox(children=(IntProgress(value=0, max=1000), HTML(value=''))), Box(children=(HTML(value=''),))))

0.9230769230769231

In [19]:
# from sklearn.model_selection import cross_val_score
# from sklearn.model_selection import LeaveOneOut
# scores = cross_val_score(m, X, Y, cv=LeaveOneOut())
# scores.mean()

In [20]:
df_s=df_s[['O*NET-SOC Code','Element Name','Data Value']]
df_a=df_a[['O*NET-SOC Code','Element Name','Data Value']]
df_k=df_k[['O*NET-SOC Code','Element Name','Data Value']]
df_w=df_w[['O*NET-SOC Code','Element Name','Data Value']]
df_c=df_c[['O*NET-SOC Code','Element Name','Data Value']]
df_zong= pd.concat( [df_s, df_a,df_k,df_w,df_c], axis=0 )
df_zong=df_zong.sort_values(by=['O*NET-SOC Code','Element Name'])
# df_zong.to_csv('967个职业各自的九个变量.csv')

In [20]:
# 全部职业(967)的计算机化率